pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: Docker build
  inputs:
    script: docker build -t kotatsuclub/cache:$(Build.SourceBranchName) .

- task: Docker@2
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: Docker push
  inputs:
    containerRegistry: dockerhub
    command: push
    repository: kotatsuclub/cache
    tags: $(Build.SourceBranchName)